bathroomSim: bathroomSim.c
	gcc -Wall -pthread -o bathroomSim bathroomSim.c bathroom.c -lm
all: bathroomSim.c
	gcc -Wall -pthread -o bathroomSim bathroomSim.c bathroom.c -lm 
clean:
	rm bathroomSim
	
